/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as BibliographyRouteImport } from './routes/bibliography'
import { Route as BackgroundRouteImport } from './routes/background'
import { Route as IndexRouteImport } from './routes/index'

const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliographyRoute = BibliographyRouteImport.update({
  id: '/bibliography',
  path: '/bibliography',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRoute = BackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/bibliography': typeof BibliographyRoute
  '/construction': typeof ConstructionRoute
  '/impact': typeof ImpactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/bibliography': typeof BibliographyRoute
  '/construction': typeof ConstructionRoute
  '/impact': typeof ImpactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/bibliography': typeof BibliographyRoute
  '/construction': typeof ConstructionRoute
  '/impact': typeof ImpactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/background' | '/bibliography' | '/construction' | '/impact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/background' | '/bibliography' | '/construction' | '/impact'
  id:
    | '__root__'
    | '/'
    | '/background'
    | '/bibliography'
    | '/construction'
    | '/impact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRoute: typeof BackgroundRoute
  BibliographyRoute: typeof BibliographyRoute
  ConstructionRoute: typeof ConstructionRoute
  ImpactRoute: typeof ImpactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliography': {
      id: '/bibliography'
      path: '/bibliography'
      fullPath: '/bibliography'
      preLoaderRoute: typeof BibliographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRoute: BackgroundRoute,
  BibliographyRoute: BibliographyRoute,
  ConstructionRoute: ConstructionRoute,
  ImpactRoute: ImpactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
